services:
  llama3.2:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS=llama3.2
  qwen3:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    environment:
      - OLLAMA_MODELS=qwen2.5

  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - "9411:9411"

  a2a-ui:
    build:
      context: .
      dockerfile: Dockerfile.a2a
    ports:
      - "12000:12000"
    profiles:
      - a2a
