spring:

  ai:
    mcp:
      client:
        enabled: true
        name: embabel
        version: 1.0.0
        request-timeout: 30s
        type: SYNC

        stdio:
          connections:
            # MCP server exposed by Docker Desktop MCP Toolkit extension
            docker-mcp:
              command: docker
              args:
                - mcp
                - gateway
                - run
                - --verbose
